# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: publish artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: nsdc_artifact
        path: /home/runner/work/torches-and-terrors/torches-and-terrors/
